### PR TITLE
Add Project README and LICENSE Drafts

### PR DESCRIPTION
**Pull request by selvinortiz**
## Initial draft for project readme and license

- Add README.md skeleton with app requirements and setup instructions
- Add MIT license and note in README.md that Valorize App is open source
- Add Valorize logo (./valorize.png) to display in README.md

Questions:
1. Is `valorize.png` used in `README.md` fine in the project root?
2. Should the MIT license an org entity or is the founder's name fine for now?

### CODE REVIEW

**Comment by javier123454321** [comment]
This looks good to me except for one tiny update, once you update that I'll do the merge. 

Thanks, I did mean update the .env.example. Also good touch on linking the discord!

**Comment by selvinortiz** [comment]
@javier123454321 Hey Javi, can you tell me what updates you'd like me to make? It wasn't listed in your comment above and I didn't see an issue or todo related to this PR. Happy to make any changes you'd like!

**Comment by javier123454321** [comment]
Sorry about that. The comment was here can you access it? https://github.com/ValorizeDAO/valorize_app/pull/38#discussion_r739591723

**Comment by javier123454321** [comment]
So the only thing is to update 5 in the .env setup to this:
5. You will also need to set up a keystore file for the operations that require accessing testnet. One way to get one is to generate it by downloading geth, creating a new account, then copying the contents of your keystore json as the environment variable.
[geth account setup instructions](https://geth.ethereum.org/docs/interface/managing-your-accounts)

**Comment by selvinortiz** [comment]
I see it now, I'll get on it.

**Pull request merged**
